version: '3.8'

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres-db-volume:
  pgadmin-data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: projeto_dbt_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow123
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airflow-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: projeto_dbt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - airflow-net
    depends_on:
      - postgres
    restart: unless-stopped

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: projeto_dbt_airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret_key_change_in_production
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres:5432/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
      - ../dbt_project:/opt/dbt_project
    ports:
      - "8080:8080"
    networks:
      - airflow-net
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Aguardando PostgreSQL...' &&
      sleep 10 &&
      airflow db init &&
      airflow webserver
      "
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: projeto_dbt_airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres:5432/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
      - ../dbt_project:/opt/dbt_project
    networks:
      - airflow-net
    depends_on:
      postgres:
        condition: service_healthy
    command: airflow scheduler
    restart: unless-stopped